#!/bin/bash

GOROOT=/usr/local/go

echo "Fixing permissions"
cd $GOROOT
find . -exec chmod ugo+r \{\} \;
find bin -exec chmod ugo+rx \{\} \;
find . -type d -exec chmod ugo+rx \{\} \;
chmod o-w .

echo "Installing miscellaneous files:"
XCODE_MISC_DIR="/Library/Application Support/Developer/Shared/Xcode/Specifications/"
if [ -d "$XCODE_MISC_DIR" ]; then
	echo "  XCode"
	cp $GOROOT/misc/xcode/* $XCODE_MISC_DIR
fi

echo "Creating Go folder in $HOME"
cd $HOME
mkdir Go
cd Go
mkdir pkg
mkdir src
mkdir bin

GOPATH=$HOME/Go
PATH=$PATH:$GOPATH

launchctl setenv GOPATH $GOPATH
launchctl setenv PATH $PATH